/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDirectoryRouteImport } from './routes/admin.directory'
import { Route as AdminIncomeRouteImport } from './routes/admin.income'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncomeRoute = AdminIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/public': typeof PublicRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/public': typeof PublicRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/public': typeof PublicRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/public'
    | '/admin/directory'
    | '/admin/income'
    | '/admin/overview'
    | '/admin/tenants'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/public'
    | '/admin/directory'
    | '/admin/income'
    | '/admin/overview'
    | '/admin/tenants'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/public'
    | '/admin/directory'
    | '/admin/income'
    | '/admin/overview'
    | '/admin/tenants'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/directory': {
      id: '/admin/directory'
      path: '/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/income': {
      id: '/admin/income'
      path: '/income'
      fullPath: '/admin/income'
      preLoaderRoute: typeof AdminIncomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDirectoryRoute: typeof AdminDirectoryRoute
  AdminIncomeRoute: typeof AdminIncomeRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDirectoryRoute: AdminDirectoryRoute,
  AdminIncomeRoute: AdminIncomeRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
